alias: 네이버 날씨 라벨 2.1
description: ""
triggers:
  - trigger: time
    at: "08:00:00"
  - trigger: time
    at: "11:00:00"
  - trigger: time
    at: "14:00:00"
  - trigger: time
    at: "17:00:00"
conditions: []
actions:
  - action: gicisky.write
    data:
      payload:
        - type: icon
          value: |
            weather-{{ states('weather.naver') }}
          anchor: lm
          x: 5
          "y": 45
          size: 90
          color: black
        - type: text
          value: |
            {% set rain = states('sensor.sigandanggangsuryang') %}
            {% set start = states('sensor.bisijagsiganoneul') %}
            {{ '비 ' + rain + 'mm' if rain != '0' else start if start != '비안옴' else start }}
          font: fonts/GmarketSansTTFBold.ttf
          anchor: lb
          x: 5
          "y": 115
          size: 21
          color: |
            {% set rain = states('sensor.sigandanggangsuryang') %}
            {% set start = states('sensor.bisijagsiganoneul') %}
            {{ 'red' if rain != '0' else 'red' if start != '비안옴' else 'black' }}
        - type: text
          value: "{{ state_attr('weather.naver', 'friendly_name') }}"
          font: fonts/GmarketSansTTFBold.ttf
          anchor: rt
          x: 245
          "y": 30
          size: 40
          color: black
        - type: text
          value: >
            {{ state_attr('weather.naver', 'temperature') }}
          font: fonts/GmarketSansTTFBold.ttf
          anchor: rb
          x: 215
          "y": 110
          size: 40
          color: black
        - type: text
          value: >
            {{ state_attr('weather.naver', 'temperature_unit') }}
          font: fonts/GmarketSansTTFBold.ttf
          anchor: rb
          x: 245
          "y": 100
          size: 20
          color: black
        - type: text
          value: "{{ now().strftime('%H시') }} 기준"
          font: fonts/GmarketSansTTFBold.ttf
          anchor: rt
          x: 240
          "y": 5
          size: 20
          color: black

    target:
      device_id:
        - 05315aa301183818e27d239ee9b7da5a
mode: single
