alias: 날짜 라벨
description: ""
triggers:
  - trigger: time
    at: "00:00:00"
conditions: []
actions:
  - action: gicisky.write
    data:
      payload:
        - type: text
          value: "{{ now().strftime('%m월 %d일') }}"
          font: fonts/NotoSansKR-Bold.ttf
          anchor: mt
          x: 125
          "y": 10
          size: 45
          color: black
        - type: text
          value: |
            {% set day_map = {
                'Monday': '월요일',
                'Tuesday': '화요일',
                'Wednesday': '수요일',
                'Thursday': '목요일',
                'Friday': '금요일',
                'Saturday': '토요일',
                'Sunday': '일요일'
            } %} {{ day_map[now().strftime('%A')] }}
          font: fonts/NotoSansKR-Bold.ttf
          anchor: mb
          x: 125
          "y": 108
          size: 45
          color: |
            {% set date = now().strftime('%A') %}
            {{ 'red' if date == 'Saturday' or date == 'Sunday' else 'black' }}
    target:
      device_id: 84cd077d3c883242348f7a2ce0fb3c75
mode: single
