alias: Wifi 라벨
description: ""
triggers: []
conditions: []
actions:
  - action: gicisky.write
    data:
      payload:
        - type: text
          value: WIFI
          font: fonts/GmarketSansTTFBold.ttf
          anchor: mt
          x: 180
          "y": 20
          size: 30
          color: black
        - type: text
          value: 카메라로 스캔하세요
          font: fonts/GmarketSansTTFBold.ttf
          anchor: mt
          x: 180
          "y": 64
          size: 15
          color: black
        - type: qrcode
          data: WIFI:T:WPA2;S:ssid;P:passwod;;
          x: 5
          "y": 10
          boxsize: 3.5
          border: 1
          color: black
    target:
      device_id: bf1eead6141be50e7ac6e50369ca06fc
mode: single
