alias: 캘린터 라벨
description: ""
triggers:
  - trigger: time
    at: "00:00:00"
conditions: []
actions:
  - variables:
      response: null
  - action: calendar.get_events
    metadata: {}
    data:
      duration:
        hours: 72
        minutes: 0
        seconds: 0
    response_variable: response
    target:
      entity_id: calendar.google
  - variables:
      today_event: |
        {% set today = now().date() %}
        {% set events = response['calendar.google'].events %}
        {% set ns = namespace(event='') %}
        {% for ev in events %}
          {% set start = as_datetime(ev.start).date() %}
          {% set end = as_datetime(ev.end).date() %}
          {% if start <= today <= end %}
            {% set ns.event = ev %}
          {% endif %}
        {% endfor %}
        {{ ns.event }}
  - action: gicisky.write
    data:
      payload:
        - type: text
          value: "{{ now().strftime('%m월 %d일') }}"
          font: fonts/GmarketSansTTFBold.ttf
          anchor: rt
          x: 175
          "y": 5
          size: 35
          color: black
        - type: text
          value: |
            {% set day_map = {
                'Monday': '월요일',
                'Tuesday': '화요일',
                'Wednesday': '수요일',
                'Thursday': '목요일',
                'Friday': '금요일',
                'Saturday': '토요일',
                'Sunday': '일요일'
            } %} {{ day_map[now().strftime('%A')] }}
          font: fonts/GmarketSansTTFBold.ttf
          anchor: lt
          x: 190
          "y": 5
          size: 35
          color: |
            {% set date = now().strftime('%A') %}
            {{ 'red' if date == 'Saturday' or date == 'Sunday' else 'black' }}
        - type: text
          value: |
            {% if today_event %}
              {{ today_event.summary }}
            {% else %}
              일정 없음
            {% endif %}
          font: fonts/GmarketSansTTFBold.ttf
          anchor: mb
          x: 148
          "y": 90
          size: 40
        - type: text
          value: |
            {% if today_event %}
              {{ as_datetime(today_event.start).strftime('%H:%M') }}
            {% endif %}
          font: fonts/GmarketSansTTFBold.ttf
          anchor: mb
          x: 148
          "y": 120
          size: 20
    target:
      device_id: 0f57b91cca28410f0648a34076ba3507
mode: single
