alias: 4.2 일간 날씨
description: ""
triggers:
  - trigger: time_pattern
    hours: /1
conditions: []
actions:
  - action: gicisky.write
    metadata: {}
    data:
      payload:
        - type: text
          value: "{{ now().strftime('%H시') }} 기준"
          font: fonts/CookieRunBold.ttf
          anchor: rt
          x: 380
          "y": 10
          size: 20
          color: black
        - type: text
          value: "{{ now().strftime('%m월') }}"
          font: fonts/CookieRunBold.ttf
          anchor: lt
          x: 10
          "y": 10
          size: 20
          color: black
        - type: text
          value: "{{ now().strftime('%d') }}"
          font: fonts/CookieRunBold.ttf
          anchor: mt
          x: 80
          "y": 40
          size: 120
          color: |
            {% set date = now().strftime('%A') %}
            {{ 'red' if date == 'Saturday' or date == 'Sunday' else 'black' }}
        - type: text
          value: |
            {% set day_map = {
                'Monday': '월요일',
                'Tuesday': '화요일',
                'Wednesday': '수요일',
                'Thursday': '목요일',
                'Friday': '금요일',
                'Saturday': '토요일',
                'Sunday': '일요일'
            } %} {{ day_map[now().strftime('%A')] }}
          font: fonts/CookieRunBold.ttf
          anchor: rt
          x: 380
          "y": 40
          size: 40
          color: |
            {% set date = now().strftime('%A') %}
            {{ 'red' if date == 'Saturday' or date == 'Sunday' else 'black' }}
        - type: text
          value: "{{ state_attr('weather.naver', 'friendly_name') }}"
          font: fonts/CookieRunBold.ttf
          anchor: rt
          x: 380
          "y": 90
          size: 40
          color: black
        - type: icon
          value: |
            weather-{{ states('weather.naver') }}
          anchor: lb
          x: 10
          "y": 230
          size: 80
          color: black
        - type: text
          value: >
            {% set rain = states('sensor.sigandanggangsuryang') %} {% set start
            = states('sensor.bisijagsiganoneul') %} {{ '비 ' + rain + 'mm' if
            rain != '0' else start + ' 비 예보' if start != '비안옴' else start }}
          font: fonts/OwnglyphParkDaHyun.ttf
          anchor: mb
          x: 170
          "y": 210
          size: 40
          color: |
            {% set rain = states('sensor.sigandanggangsuryang') %}
            {% set start = states('sensor.bisijagsiganoneul') %}
            {{ 'red' if rain != '0' else 'red' if start != '비안옴' else 'black' }}
        - type: text
          value: |
            {{ states('sensor.hyeonjaeondo') }}
          font: fonts/CookieRunBold.ttf
          anchor: rb
          x: 360
          "y": 200
          size: 50
          color: black
        - type: text
          value: |
            {{ state_attr('sensor.hyeonjaeondo', 'unit_of_measurement') }}
          font: fonts/CookieRunBold.ttf
          anchor: rb
          x: 380
          "y": 190
          size: 20
          color: black
        - type: text
          value: |
            {{ states('sensor.coejeoondo') }} / {{ states('sensor.coegoondo') }}
          font: fonts/CookieRunBold.ttf
          anchor: rb
          x: 360
          "y": 240
          size: 30
          color: black
        - type: text
          value: "{{ states('sensor.hyeonjaenalssijeongbo') }}"
          font: fonts/OwnglyphParkDaHyun.ttf
          anchor: mb
          x: 200
          "y": 280
          size: 25
          color: black
    target:
      device_id: 8f69c732cd0aef9a2c879f5de5634445
mode: single
