alias: 날짜 라벨
description: ""
triggers:
  - trigger: time
    at: "00:00:00"
conditions: []
actions:
  - action: gicisky.write
    data:
      background: black
      rotate: 270
      payload:
        - type: text
          value: "{{ now().strftime('%m월 %d일') }}"
          font: fonts/OwnglyphParkDaHyun.ttf
          anchor: mt
          x: 240
          "y": 110
          size: 100
          color: white
        - type: text
          value: |
            {% set day_map = {
                'Monday': '월요일',
                'Tuesday': '화요일',
                'Wednesday': '수요일',
                'Thursday': '목요일',
                'Friday': '금요일',
                'Saturday': '토요일',
                'Sunday': '일요일'
            } %} {{ day_map[now().strftime('%A')] }}
          font: fonts/OwnglyphParkDaHyun.ttf
          anchor: mt
          x: 240
          "y": 220
          size: 100
          color: |
            {% set date = now().strftime('%A') %}
            {{ 'red' if date == 'Saturday' or date == 'Sunday' else 'white' }}
        - type: icon
          value: |
            weather-{{ states('weather.naver') }}
          anchor: lt
          x: 30
          "y": 400
          size: 180
          color: white
        - type: text
          value: "{{ states('sensor.hyeonjaenalssijeongbo') }}"
          font: fonts/OwnglyphParkDaHyun.ttf
          anchor: mt
          x: 240
          "y": 600
          size: 50
          color: white
        - type: text
          value: >
            {% set rain = states('sensor.sigandanggangsuryang') %}

            {% set start = states('sensor.bisijagsiganoneul') %}

            {{ '비 ' + rain + 'mm' if rain != '0' else start + ' 비 예보' if start
            != '비안옴' else start }}
          font: fonts/OwnglyphParkDaHyun.ttf
          anchor: mt
          x: 240
          "y": 700
          size: 80
          color: |
            {% set rain = states('sensor.sigandanggangsuryang') %}
            {% set start = states('sensor.bisijagsiganoneul') %}
            {{ 'red' if rain != '0' else 'red' if start != '비안옴' else 'white' }}
        - type: text
          value: "{{ state_attr('weather.naver', 'friendly_name') }}"
          font: fonts/OwnglyphParkDaHyun.ttf
          anchor: rt
          x: 440
          "y": 350
          size: 90
          color: white
        - type: text
          value: |
            {{ state_attr('weather.naver', 'temperature') }}
          font: fonts/OwnglyphParkDaHyun.ttf
          anchor: rb
          x: 390
          "y": 550
          size: 120
          color: white
        - type: text
          value: |
            {{ state_attr('weather.naver', 'temperature_unit') }}
          font: fonts/OwnglyphParkDaHyun.ttf
          anchor: rb
          x: 450
          "y": 550
          size: 60
          color: white
        - type: text
          value: "{{ now().strftime('%H시') }} 기준"
          font: fonts/OwnglyphParkDaHyun.ttf
          anchor: rt
          x: 450
          "y": 20
          size: 50
          color: white
    target:
      device_id: 2766ccde02539d2b8cfe034556aa95ae
mode: single
