alias: 7.5 종합
description: ""
triggers:
  - trigger: time_pattern
    hours: /1
conditions: []
actions:
  - action: gicisky.write
    data:
      rotate: 270
      payload:
        - type: text
          value: "{{ now().strftime('%H시') }} 기준"
          font: fonts/CookieRunBold.ttf
          anchor: rt
          x: 450
          "y": 20
          size: 40
          color: black
        - type: text
          value: "{{ now().strftime('%m월') }}"
          font: fonts/CookieRunBold.ttf
          anchor: lt
          x: 20
          "y": 20
          size: 40
          color: black
        - type: text
          value: "{{ now().strftime('%d') }}"
          font: fonts/CookieRunBold.ttf
          anchor: mt
          x: 120
          "y": 120
          size: 180
          color: |
            {% set date = now().strftime('%A') %}
            {{ 'red' if date == 'Saturday' or date == 'Sunday' else 'black' }}
        - type: text
          value: |
            {% set day_map = {
                'Monday': '월요일',
                'Tuesday': '화요일',
                'Wednesday': '수요일',
                'Thursday': '목요일',
                'Friday': '금요일',
                'Saturday': '토요일',
                'Sunday': '일요일'
            } %} {{ day_map[now().strftime('%A')] }}
          font: fonts/CookieRunBold.ttf
          anchor: mt
          x: 360
          "y": 100
          size: 80
          color: |
            {% set date = now().strftime('%A') %}
            {{ 'red' if date == 'Saturday' or date == 'Sunday' else 'black' }}
        - type: text
          value: "{{ state_attr('weather.naver', 'friendly_name') }}"
          font: fonts/CookieRunBold.ttf
          anchor: mt
          x: 360
          "y": 200
          size: 80
          color: black
        - type: icon
          value: |
            weather-{{ states('weather.naver') }}
          anchor: lb
          x: 30
          "y": 450
          size: 180
          color: black
        - type: text
          value: |
            {{ states('sensor.hyeonjaeondo') }}
          font: fonts/CookieRunBold.ttf
          anchor: rb
          x: 390
          "y": 390
          size: 80
          color: black
        - type: text
          value: |
            {{ state_attr('sensor.hyeonjaeondo', 'unit_of_measurement') }}
          font: fonts/CookieRunBold.ttf
          anchor: rb
          x: 450
          "y": 390
          size: 40
          color: black
        - type: text
          value: |
            {{ states('sensor.coejeoondo') }} / {{ states('sensor.coegoondo') }}
          font: fonts/CookieRunBold.ttf
          anchor: rb
          x: 390
          "y": 435
          size: 40
          color: black
        - type: text
          value: "{{ states('sensor.hyeonjaenalssijeongbo') }}"
          font: fonts/OwnglyphParkDaHyun.ttf
          anchor: mt
          x: 240
          "y": 500
          size: 45
          color: black
        - type: text
          value: >
            {% set rain = states('sensor.sigandanggangsuryang') %} {% set start
            = states('sensor.bisijagsiganoneul') %} {{ '비 ' + rain + 'mm' if
            rain != '0' else start + ' 비 예보' if start != '비안옴' else start }}
          font: fonts/OwnglyphParkDaHyun.ttf
          anchor: mt
          x: 240
          "y": 550
          size: 80
          color: |
            {% set rain = states('sensor.sigandanggangsuryang') %}
            {% set start = states('sensor.bisijagsiganoneul') %}
            {{ 'red' if rain != '0' else 'red' if start != '비안옴' else 'black' }}
        - type: text
          value: 거실
          font: fonts/CookieRunBold.ttf
          anchor: mb
          x: 60
          "y": 730
          size: 35
          color: black
        - type: text
          value: 안방
          font: fonts/CookieRunBold.ttf
          anchor: mb
          x: 150
          "y": 730
          size: 35
          color: black
        - type: text
          value: 방1
          font: fonts/CookieRunBold.ttf
          anchor: mb
          x: 240
          "y": 730
          size: 35
          color: black
        - type: text
          value: 방2
          font: fonts/CookieRunBold.ttf
          anchor: mb
          x: 330
          "y": 730
          size: 35
          color: black
        - type: text
          value: 거실2
          font: fonts/CookieRunBold.ttf
          anchor: mb
          x: 420
          "y": 730
          size: 35
          color: black
        - type: text
          value: >
            {{ state_attr('climate.esp_kocom_livingroom_heater',
            'current_temperature') }}
          font: fonts/CookieRunBold.ttf
          anchor: mb
          x: 60
          "y": 780
          size: 50
          color: |
            {% if is_state('climate.esp_kocom_livingroom_heater', 'off') %}
              black
            {% else %}
              red
            {% endif %}
        - type: text
          value: >
            {{ state_attr('climate.esp_kocom_bedroom_heater',
            'current_temperature') }}
          font: fonts/CookieRunBold.ttf
          anchor: mb
          x: 150
          "y": 780
          size: 50
          color: |
            {% if is_state('climate.esp_kocom_bedroom_heater', 'off') %}
              black
            {% else %}
              red
            {% endif %}
        - type: text
          value: >
            {{ state_attr('climate.esp_kocom_room_1_heater',
            'current_temperature') }}
          font: fonts/CookieRunBold.ttf
          anchor: mb
          x: 240
          "y": 780
          size: 50
          color: |
            {% if is_state('climate.esp_kocom_room_1_heater', 'off') %}
              black
            {% else %}
              red
            {% endif %}
        - type: text
          value: >
            {{ state_attr('climate.esp_kocom_room_2_heater',
            'current_temperature') }}
          font: fonts/CookieRunBold.ttf
          anchor: mb
          x: 330
          "y": 780
          size: 50
          color: |
            {% if is_state('climate.esp_kocom_room_2_heater', 'off') %}
              black
            {% else %}
              red
            {% endif %}
        - type: text
          value: >
            {{ state_attr('climate.esp_kocom_livingroom_2_heater',
            'current_temperature') }}
          font: fonts/CookieRunBold.ttf
          anchor: mb
          x: 420
          "y": 780
          size: 50
          color: |
            {% if is_state('climate.esp_kocom_livingroom_2_heater', 'off') %}
              black
            {% else %}
              red
            {% endif %}
    target:
      device_id: 2766ccde02539d2b8cfe034556aa95ae
    enabled: true
mode: single
