alias: 이미지 라벨
description: ""
triggers: []
conditions: []
actions:
  - action: gicisky.write
    data:
      payload:
        - type: dlimg
          url: /config/www/images/image.png
          x: 0
          "y": 0
          xsize: 800
          ysize: 480
    target:
      device_id: dfce78828e18592acb89c4282eacfd70
mode: single
